In [2]:
# Label Encoding Basic Example One
from sklearn.preprocessing import LabelEncoder

colors=['Red','Blue','Green','Blue','Red']

le=LabelEncoder()
# fit and transform
encoded=le.fit_transform(colors)

print(encoded)

[2 0 1 0 2]


In [6]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

data=pd.DataFrame({'color':['Red','Blue','Green','Blue','Red']})

# Create encoder
ohe=OneHotEncoder(sparse_output=False)

#Fit and transform
encoded=ohe.fit_transform(data[['color']])
print(encoded)
encoded_df=pd.DataFrame(encoded, columns=ohe.get_feature_names_out(['color']))
print(encoded_df)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
   color_Blue  color_Green  color_Red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         1.0          0.0        0.0
4         0.0          0.0        1.0


In [9]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

data=pd.DataFrame({'Satisfaction':['Low','Medium','High','Low']})
le=LabelEncoder()
data['Satisfaction_Encoded']=le.fit_transform(data['Satisfaction'])
print(data)

  Satisfaction  Satisfaction_Encoded
0          Low                     1
1       Medium                     2
2         High                     0
3          Low                     1


In [10]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

data=pd.DataFrame({'Region':['North','South','East','West','South']})
ohe=OneHotEncoder(sparse_output=False)
encoded=ohe.fit_transform(data[['Region']])
encoded_df=pd.DataFrame(encoded, columns=ohe.get_feature_names_out(['Region']))
print(encoded_df)

   Region_East  Region_North  Region_South  Region_West
0          0.0           1.0           0.0          0.0
1          0.0           0.0           1.0          0.0
2          1.0           0.0           0.0          0.0
3          0.0           0.0           0.0          1.0
4          0.0           0.0           1.0          0.0


# Linear Regression: Find the best fitting straight line.
    ## Step 1: Collect the data.
    ## Step 2: Create the model for linear regression.
    ## Step 3: Train the model. = fit(x,y)
    ## Step 4: Predict the result. = predict([[value_to_predict]])
    ## Step 5: (optional) = Visualize using plot of best fitted.

In [11]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [15]:
hours_studied=np.array([[1], [2], [3], [4], [5], [6], [7], [8]])
marks_obtained=np.array([20,25,30,35,50,60,70,80])

In [16]:
##Step 2: Create the model for linear Regression
model=LinearRegression()

In [18]:
#Step 3: Train the model fit(x,y)
model.fit(hours_studied, marks_obtained)

LinearRegression()

In [19]:
##Step 4: Predict the result predict([[value_to_predict]])
predicted_marks=model.predict([[9]])
print('Predicted Marks for 9 hours', predicted_marks)

Predicted Marks for 9 hours [86.42857143]


In [21]:
hour_study=float(input('Number of hours to study to predict marks'))
p_marks=model.predict([[hour_study]])
print(f'predicted marks for {hour_study} hours is likely {p_marks}')

Number of hours to study to predict marks 8


predicted marks for 8.0 hours is likely [77.5]


In [22]:
pri*3

NameError: name 'Hi' is not defined