# We are going to start TensorFlow Basics here 🥱

In [ ]:
import tensorflow as tf

In [ ]:
print(tf.__version__)

2.19.0


In [ ]:
#Creating Tensor with constant
#function here that we can use to create
scalar=tf.constant(9)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [ ]:
scalar.ndim

0

In [ ]:
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
matrix=tf.constant([[5,9],[9,11]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5,  9],
       [ 9, 11]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
second_matrix=tf.constant([[5,7],
                           [3,8],
                           [3,9],
                           [4,2],
                           [8,6]])

In [ ]:
second_matrix

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[5, 7],
       [3, 8],
       [3, 9],
       [4, 2],
       [8, 6]], dtype=int32)>

In [ ]:
second_matrix.ndim

2

In [ ]:
third_matrix=tf.constant(
    [
        [[1,2,3],
        [2,4,5]],
        [[7,9,3],
        [10,4,5]],
        [[11,2,3],
        [2,4,15]],
                 ])
third_matrix

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 2,  4,  5]],

       [[ 7,  9,  3],
        [10,  4,  5]],

       [[11,  2,  3],
        [ 2,  4, 15]]], dtype=int32)>

In [ ]:
third_matrix.ndim

3

In [ ]:
second_matrix=tf.constant([[5.6,7.3], [3.45,8],
                           [3.11,9.23],
                           [3.3,9.67],
                           [8.4,2.3]
                            ])
print(second_matrix)

tf.Tensor(
[[5.6  7.3 ]
 [3.45 8.  ]
 [3.11 9.23]
 [3.3  9.67]
 [8.4  2.3 ]], shape=(5, 2), dtype=float32)


In [ ]:
# a number with direction
vector=tf.constant([10,10,20,30])
vector

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([10, 10, 20, 30], dtype=int32)>

In [ ]:
# 2D array of numbers
matrix=tf.constant([[10,20],[30,40]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [ ]:
# Tensor: an n-dimensions array of numbers (n=0, n=1, n=2.......)
tensor=tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]])
tensor

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int32)>

In [ ]:
# Find the shape, rank and size of tensors
print('Scalar Information')
print('Shape:',scalar.shape)
print('Dimension:',scalar.ndim)
print('Rank:',tf.rank(scalar).numpy())
print('Size:',tf.size(scalar))

Scalar Information
Shape: ()
Dimension: 0
Rank: 0
Size: tf.Tensor(1, shape=(), dtype=int32)


In [ ]:
print('Vector Information')
print('Shape:',vector.shape)
print('Dimension:',vector.ndim)
print('Rank:',tf.rank(vector).numpy())
print('Size:',tf.size(vector))

Vector Information
Shape: (4,)
Dimension: 1
Rank: 1
Size: tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
print('Matrix Information')
print('Shape:',matrix.shape)
print('Dimension:',matrix.ndim)
print('Rank:',tf.rank(matrix).numpy())
print('Size:',tf.size(matrix))

Matrix Information
Shape: (2, 2)
Dimension: 2
Rank: 2
Size: tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
print('Tensor Information')
print('Shape:',tensor.shape)
print('Dimension:',tensor.ndim)
print('Rank:',tf.rank(tensor).numpy())
print('Size:',tf.size(tensor))

Tensor Information
Shape: (2, 2, 2)
Dimension: 3
Rank: 3
Size: tf.Tensor(8, shape=(), dtype=int32)


In [ ]:
# Creating tensor using variable
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
changeable_tensor[0].assign(9)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([9, 7], dtype=int32)>

In [ ]:
changeable_tensor[1].assign(15)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 9, 15], dtype=int32)>

In [ ]:
unchangeable_tensor    #cannot assign, error!

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [ ]:
# unchangeable_tensor[0].assign(12)
# unchangebale_tensor
# this will be an error because you cant change constat tensor. They are immutable i.e unchangeable.

In [ ]:
#Random Tensors
random_tensor=tf.random.Generator.from_seed(42)
random_tensor=random_tensor.normal(shape=(3,2))
random_tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random_tensor_2=tf.random.uniform(shape=(300,150),minval=0,maxval=1)
random_tensor_2

<tf.Tensor: shape=(300, 150), dtype=float32, numpy=
array([[0.03750324, 0.60355127, 0.8041636 , ..., 0.33702934, 0.0583322 ,
        0.2311666 ],
       [0.24686575, 0.1521436 , 0.04704404, ..., 0.21235347, 0.58309686,
        0.12784421],
       [0.50260234, 0.34324384, 0.700912  , ..., 0.11105907, 0.5769069 ,
        0.6731318 ],
       ...,
       [0.9901507 , 0.90257776, 0.6062412 , ..., 0.89262724, 0.78499043,
        0.6859381 ],
       [0.5957314 , 0.5035039 , 0.616673  , ..., 0.12694561, 0.86201084,
        0.9863591 ],
       [0.14060211, 0.24887776, 0.712644  , ..., 0.03455603, 0.5733634 ,
        0.5922679 ]], dtype=float32)>

In [ ]:
# same seed same tensors
random_tensor_3=tf.random.Generator.from_seed(42)
random_tensor_3=random_tensor_3.normal(shape=(3,2))
random_tensor_4=tf.random.Generator.from_seed(42)
random_tensor_4=random_tensor_4.normal(shape=(3,2))
random_tensor_3,random_tensor_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>)

In [ ]:
# different seed different tensors
random_tensor_3=tf.random.Generator.from_seed(42)
random_tensor_3=random_tensor_3.normal(shape=(3,2))
random_tensor_4=tf.random.Generator.from_seed(15)
random_tensor_4=random_tensor_4.normal(shape=(3,2))
random_tensor_3,random_tensor_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.33149973, -0.5445254 ],
        [ 1.5222508 ,  0.59303206],
        [-0.63509274,  0.3703566 ]], dtype=float32)>)

In [ ]:
# creating tensors using zeros
tensor_zeros=tf.zeros(shape=(3,4),dtype=tf.dtypes.float32)
tensor_zeros

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
tensor_zeros=tf.zeros(shape=(3,4),dtype=tf.dtypes.int16)
tensor_zeros

<tf.Tensor: shape=(3, 4), dtype=int16, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)>

In [ ]:
# tensor for all ones
tensor_ones=tf.ones(shape=(3,4),dtype=tf.dtypes.int16)
tensor_ones

<tf.Tensor: shape=(3, 4), dtype=int16, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)>

In [ ]:
import numpy as np
numpy_Array=np.arange(1,25,dtype=np.int16)
numpy_Array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int16)

In [ ]:
tensor_numpy=tf.constant(numpy_Array,shape=(2,3,4))
tensor_numpy

<tf.Tensor: shape=(2, 3, 4), dtype=int16, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int16)>

In [ ]:
print('Tensor Information')
print('Shape:',tensor_numpy.shape)
print('Dimension:',tensor_numpy.ndim)
print('Rank:',tf.rank(tensor_numpy).numpy())
print('Size:',tf.size(tensor_numpy))
print('DataType of elements: ',tensor_numpy.dtype)
print('Elements along axis 0: ',tensor_numpy.shape[0])
print('Elements along axis 1: ',tensor_numpy.shape[1])
print('Elements along axis 2: ',tensor_numpy.shape[2])
print('Total Elements: ',tf.size(tensor_numpy).numpy())

Tensor Information
Shape: (2, 3, 4)
Dimension: 3
Rank: 3
Size: tf.Tensor(24, shape=(), dtype=int32)
DataType of elements:  <dtype: 'int16'>
Elements along axis 0:  2
Elements along axis 1:  3
Elements along axis 2:  4
Total Elements:  24


In [ ]:
# Working with items of each dimension
# Firt three elements
tensor_numpy[:3,:3,:3]


<tf.Tensor: shape=(2, 3, 3), dtype=int16, numpy=
array([[[ 1,  2,  3],
        [ 5,  6,  7],
        [ 9, 10, 11]],

       [[13, 14, 15],
        [17, 18, 19],
        [21, 22, 23]]], dtype=int16)>

In [ ]:
# First two elements of each dimensions
tensor_numpy[:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2), dtype=int16, numpy=
array([[[ 1,  2],
        [ 5,  6]],

       [[13, 14],
        [17, 18]]], dtype=int16)>

**Arthmetic Operations with Tensors** 👽

*   Add
*   Sub
*   Multi
*   Div








In [ ]:
tensor_one=tf.constant([[11,9],[2,5]])
tensor_one

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11,  9],
       [ 2,  5]], dtype=int32)>

In [ ]:
tf.add(tensor_one,15)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[26, 24],
       [17, 20]], dtype=int32)>

In [ ]:
tf.subtract(tensor_one,5)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6,  4],
       [-3,  0]], dtype=int32)>

In [ ]:
tensor_one*2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 18],
       [ 4, 10]], dtype=int32)>

In [ ]:
tensor_one/2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5.5, 4.5],
       [1. , 2.5]])>

In [ ]:
tf.square(tensor_one)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  81],
       [  4,  25]], dtype=int32)>

In [ ]:
tf.sqrt(tensor_one)

InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
	; NodeDef: {{node Sqrt}}; Op<name=Sqrt; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Sqrt] name: 

In [ ]:
second_matrix=tf.constant([[5,7],[64,25],
                           [3,8],
                           [3,9],
                           [4,2],
                           [8,6]],dtype=tf.float32)
print(second_matrix)

tf.Tensor(
[[ 5.  7.]
 [64. 25.]
 [ 3.  8.]
 [ 3.  9.]
 [ 4.  2.]
 [ 8.  6.]], shape=(6, 2), dtype=float32)


In [ ]:
tf.sqrt(second_matrix)

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[2.236068 , 2.6457512],
       [1.7320508, 2.828427 ],
       [1.7320508, 3.       ],
       [2.       , 1.4142135],
       [2.828427 , 2.4494898]], dtype=float32)>

**EXERCISE TWIMEEEEEEE**
*   Create two tensors with random values between 0 and 1, shape is [6,300].
*   Find out the following details: Number of elements (Size, Rank Shape)



In [ ]:
tensor1 = tf.random.uniform(shape=[6, 300], minval=0, maxval=1)
tensor2 = tf.random.uniform(shape=[6, 300], minval=0, maxval=1)

In [ ]:
print("Tensor 1:",tensor1)
print("Shape:", tensor1.shape)
print("Rank (number of dimensions):", tf.rank(tensor1).numpy())
print("Size (number of elements):", tf.size(tensor1).numpy())

print("\nTensor 2:",tensor2)
print("Shape:", tensor2.shape)
print("Rank (number of dimensions):", tf.rank(tensor2).numpy())
print("Size (number of elements):", tf.size(tensor2).numpy())

Tensor 1: tf.Tensor(
[[0.3389418  0.77229226 0.03102255 ... 0.94460654 0.20387983 0.94558203]
 [0.7010186  0.35552728 0.31688046 ... 0.5070522  0.86713827 0.37075853]
 [0.7520907  0.888952   0.32779574 ... 0.8994185  0.60346854 0.11327088]
 [0.78445876 0.03911483 0.5159142  ... 0.3009485  0.6163416  0.37858725]
 [0.7745708  0.99881315 0.6832278  ... 0.6242902  0.27419233 0.20054924]
 [0.9161706  0.77120364 0.20581388 ... 0.02491653 0.42237055 0.6704792 ]], shape=(6, 300), dtype=float32)
Shape: (6, 300)
Rank (number of dimensions): 2
Size (number of elements): 1800

Tensor 2: tf.Tensor(
[[0.6127522  0.10356939 0.3478831  ... 0.39201653 0.8171027  0.80045354]
 [0.55042565 0.8457501  0.3052559  ... 0.49992383 0.84885025 0.20137835]
 [0.9416474  0.78018355 0.410074   ... 0.9812975  0.90762866 0.12568974]
 [0.49738622 0.30450296 0.11333466 ... 0.05094993 0.4169439  0.73888373]
 [0.71748054 0.7710067  0.5729257  ... 0.9285703  0.67424405 0.1798768 ]
 [0.47568107 0.02825594 0.22910976 ... 0.1